import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ReactNode } from "react"

import "@/styles/globals.css"

import Providers from "@/providers/providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Animus & Mangos",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: ReactNode
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
